"""Create bible tables

Revision ID: 5786a69aae71
Revises: 
Create Date: 2025-12-26 18:59:50.668152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5786a69aae71'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bible_versions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Primary Key'),
    sa.Column('youversion_bible_id', sa.String(length=20), nullable=False, comment="YouVersion bible_id, e.g., '1392'"),
    sa.Column('abbreviation', sa.String(length=50), nullable=False, comment="English abbreviation, e.g., 'CCBT'"),
    sa.Column('title', sa.String(length=255), nullable=False, comment='English title'),
    sa.Column('localized_title', sa.String(length=255), nullable=False, comment="Localized title, e.g., '當代譯本'"),
    sa.Column('localized_abbreviation', sa.String(length=50), nullable=True, comment="Localized abbreviation, e.g., 'CCB'"),
    sa.Column('language_tag', sa.String(length=20), nullable=False, comment="Language tag, e.g., 'zh-Hant-TW'"),
    sa.Column('copyright', sa.Text(), nullable=True, comment='Copyright information'),
    sa.Column('promotional_content', sa.Text(), nullable=True, comment='Promotional content'),
    sa.Column('publisher_url', sa.String(length=500), nullable=True, comment='Publisher URL'),
    sa.Column('youversion_deep_link', sa.String(length=500), nullable=True, comment='YouVersion deep link'),
    sa.Column('organization_id', sa.UUID(), nullable=True, comment='Organization ID'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Is version active'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bible_versions')),
    schema='public',
    comment='Bible versions table'
    )
    op.create_index(op.f('ix_bible_versions_is_active'), 'bible_versions', ['is_active'], unique=False, schema='public')
    op.create_index(op.f('ix_bible_versions_language_tag'), 'bible_versions', ['language_tag'], unique=False, schema='public')
    op.create_index(op.f('ix_bible_versions_youversion_bible_id'), 'bible_versions', ['youversion_bible_id'], unique=True, schema='public')
    op.create_table('bible_books',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Primary Key'),
    sa.Column('bible_version_id', sa.UUID(), nullable=False, comment='Bible version ID'),
    sa.Column('book_code', sa.String(length=10), nullable=False, comment="Book code, e.g., 'GEN', 'MAT'"),
    sa.Column('title', sa.String(length=100), nullable=False, comment='Book title'),
    sa.Column('full_title', sa.String(length=100), nullable=True, comment='Full book title'),
    sa.Column('abbreviation', sa.String(length=10), nullable=True, comment="Book abbreviation, e.g., '創'"),
    sa.Column('canon', sa.String(length=20), nullable=False, comment="Canon type: 'old_testament' or 'new_testament'"),
    sa.Column('chapter_count', sa.Integer(), nullable=False, comment='Number of chapters in this book'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.Column('sequence', sa.Float(), server_default=sa.text('extract(epoch from now())'), nullable=True, comment='Display sort, small to large, positive sort, default value current timestamp'),
    sa.ForeignKeyConstraint(['bible_version_id'], ['public.bible_versions.id'], name=op.f('fk_bible_books_bible_version_id_bible_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bible_books')),
    sa.UniqueConstraint('bible_version_id', 'book_code', name='uq_bible_books_version_book_code'),
    schema='public',
    comment='Bible books table - books belong to a specific version'
    )
    op.create_index(op.f('ix_bible_books_bible_version_id'), 'bible_books', ['bible_version_id'], unique=False, schema='public')
    op.create_index(op.f('ix_bible_books_book_code'), 'bible_books', ['book_code'], unique=False, schema='public')
    op.create_index(op.f('ix_bible_books_canon'), 'bible_books', ['canon'], unique=False, schema='public')
    op.create_table('bible_verses',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Primary Key'),
    sa.Column('book_id', sa.UUID(), nullable=False, comment='Book ID (which also identifies the version)'),
    sa.Column('chapter', sa.Integer(), nullable=False, comment='Chapter number'),
    sa.Column('verse', sa.Integer(), nullable=False, comment='Verse number'),
    sa.Column('passage_id', sa.String(length=50), nullable=False, comment="Passage ID, e.g., 'GEN.1.1'"),
    sa.Column('content', sa.Text(), nullable=False, comment='Verse content (version-specific)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.ForeignKeyConstraint(['book_id'], ['public.bible_books.id'], name=op.f('fk_bible_verses_book_id_bible_books'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bible_verses')),
    sa.UniqueConstraint('book_id', 'chapter', 'verse', name='uq_bible_verses_book_chapter_verse'),
    sa.UniqueConstraint('book_id', 'passage_id', name='uq_bible_verses_book_passage'),
    schema='public',
    comment='Bible verses table - verse belongs to a book (which belongs to a version)'
    )
    op.create_index(op.f('ix_bible_verses_book_id'), 'bible_verses', ['book_id'], unique=False, schema='public')
    op.create_index(op.f('ix_bible_verses_chapter'), 'bible_verses', ['chapter'], unique=False, schema='public')
    op.create_index(op.f('ix_bible_verses_passage_id'), 'bible_verses', ['passage_id'], unique=False, schema='public')
    op.create_index(op.f('ix_bible_verses_verse'), 'bible_verses', ['verse'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bible_verses_verse'), table_name='bible_verses', schema='public')
    op.drop_index(op.f('ix_bible_verses_passage_id'), table_name='bible_verses', schema='public')
    op.drop_index(op.f('ix_bible_verses_chapter'), table_name='bible_verses', schema='public')
    op.drop_index(op.f('ix_bible_verses_book_id'), table_name='bible_verses', schema='public')
    op.drop_table('bible_verses', schema='public')
    op.drop_index(op.f('ix_bible_books_canon'), table_name='bible_books', schema='public')
    op.drop_index(op.f('ix_bible_books_book_code'), table_name='bible_books', schema='public')
    op.drop_index(op.f('ix_bible_books_bible_version_id'), table_name='bible_books', schema='public')
    op.drop_table('bible_books', schema='public')
    op.drop_index(op.f('ix_bible_versions_youversion_bible_id'), table_name='bible_versions', schema='public')
    op.drop_index(op.f('ix_bible_versions_language_tag'), table_name='bible_versions', schema='public')
    op.drop_index(op.f('ix_bible_versions_is_active'), table_name='bible_versions', schema='public')
    op.drop_table('bible_versions', schema='public')
    # ### end Alembic commands ###
