"""Move locale to the device and add the reonboarding flag

Revision ID: ac38a16de6a6
Revises: cb4541c4145b
Create Date: 2026-09-08 12:49:36.217077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac38a16de6a6'
down_revision: Union[str, Sequence[str], None] = 'cb4541c4145b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('reonboarding_requested_at', sa.DateTime(timezone=True), nullable=True, comment='When an Admin asked this End user to replay onboarding; cleared once the client acknowledges it'), schema='app')
    op.drop_column('user_preferences', 'locale', schema='app')
    op.add_column('device', sa.Column('locale', sa.String(length=20), nullable=True, comment="This install's last-known system locale, used to localize push copy (ADR 0009)"), schema='push')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'locale', schema='push')
    op.add_column('user_preferences', sa.Column('locale', sa.VARCHAR(length=10), server_default=sa.text("'zh-Hant'::character varying"), autoincrement=False, nullable=True, comment='Locale tag'), schema='app')
    op.drop_column('user', 'reonboarding_requested_at', schema='app')
    # ### end Alembic commands ###
