"""add user preferences week start

Revision ID: 41bf5860475c
Revises: b1c43c0b358a
Create Date: 2026-09-08 21:44:21.579942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41bf5860475c'
down_revision: Union[str, Sequence[str], None] = 'b1c43c0b358a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preferences', sa.Column('week_start', sa.String(length=10), server_default='sunday', nullable=False, comment='Week start: sunday|monday'), schema='app')
    op.create_check_constraint(op.f('ck_user_preferences_week_start'), 'user_preferences', "week_start IN ('sunday', 'monday')", schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_user_preferences_week_start'), 'user_preferences', schema='app', type_='check')
    op.drop_column('user_preferences', 'week_start', schema='app')
    # ### end Alembic commands ###
