"""add daily devotion tables

Revision ID: b1c43c0b358a
Revises: ac38a16de6a6
Create Date: 2026-09-08 16:44:31.379175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b1c43c0b358a'
down_revision: Union[str, Sequence[str], None] = 'ac38a16de6a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute('CREATE SCHEMA IF NOT EXISTS devotion')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devotions',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('passage_start', sa.String(length=50), nullable=False, comment='First bible.verses passage_id'),
    sa.Column('passage_end', sa.String(length=50), nullable=False, comment='Last bible.verses passage_id'),
    sa.Column('status', sa.String(length=10), server_default='draft', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.CheckConstraint("status IN ('draft', 'ready')", name=op.f('ck_devotions_devotion_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devotions')),
    schema='devotion',
    comment='Devotion editorial content pool'
    )
    op.create_index(op.f('ix_devotions_status'), 'devotions', ['status'], unique=False, schema='devotion')
    op.create_table('daily_lesson_schedule',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('devotion_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.ForeignKeyConstraint(['devotion_id'], ['devotion.devotions.id'], name=op.f('fk_daily_lesson_schedule_devotion_id_devotions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_lesson_schedule')),
    sa.UniqueConstraint('date', name=op.f('uq_daily_lesson_schedule_date')),
    schema='devotion',
    comment='One scheduled Devotion per calendar date'
    )
    op.create_index(op.f('ix_daily_lesson_schedule_devotion_id'), 'daily_lesson_schedule', ['devotion_id'], unique=False, schema='devotion')
    op.create_table('translations',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('devotion_id', sa.UUID(), nullable=False),
    sa.Column('locale_id', sa.UUID(), nullable=False),
    sa.Column('reflect', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Ordered reflection prompt strings'),
    sa.Column('apply', sa.Text(), nullable=False, comment="Today's application"),
    sa.Column('pray', sa.Text(), nullable=False, comment='Prayer'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.ForeignKeyConstraint(['devotion_id'], ['devotion.devotions.id'], name=op.f('fk_translations_devotion_id_devotions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['locale_id'], ['public.system_locale.id'], name=op.f('fk_translations_locale_id_system_locale')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_translations')),
    sa.UniqueConstraint('devotion_id', 'locale_id', name=op.f('uq_translations_devotion_id_locale_id')),
    schema='devotion',
    comment='Locale-specific authored Devotion content'
    )
    op.create_index(op.f('ix_translations_devotion_id'), 'translations', ['devotion_id'], unique=False, schema='devotion')
    op.create_index(op.f('ix_translations_locale_id'), 'translations', ['locale_id'], unique=False, schema='devotion')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_translations_locale_id'), table_name='translations', schema='devotion')
    op.drop_index(op.f('ix_translations_devotion_id'), table_name='translations', schema='devotion')
    op.drop_table('translations', schema='devotion')
    op.drop_index(op.f('ix_daily_lesson_schedule_devotion_id'), table_name='daily_lesson_schedule', schema='devotion')
    op.drop_table('daily_lesson_schedule', schema='devotion')
    op.drop_index(op.f('ix_devotions_status'), table_name='devotions', schema='devotion')
    op.drop_table('devotions', schema='devotion')
    # ### end Alembic commands ###
    op.execute('DROP SCHEMA IF EXISTS devotion')
