"""add encounter day rhythm

Revision ID: 4a2cf18c310c
Revises: 41bf5860475c
Create Date: 2026-09-08 22:59:50.846711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a2cf18c310c'
down_revision: Union[str, Sequence[str], None] = '41bf5860475c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('encounter_days',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.ForeignKeyConstraint(['user_id'], ['app.user.id'], name=op.f('fk_encounter_days_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_encounter_days')),
    sa.UniqueConstraint('user_id', 'date', name=op.f('uq_encounter_days_user_id_date')),
    schema='devotion',
    comment='One private Encounter day per End user and date'
    )
    op.create_index(op.f('ix_encounter_days_date'), 'encounter_days', ['date'], unique=False, schema='devotion')
    op.create_index(op.f('ix_encounter_days_user_id'), 'encounter_days', ['user_id'], unique=False, schema='devotion')
    op.create_table('encounter_streaks',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), server_default='0', nullable=False),
    sa.Column('current_streak_length', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_encounter_date', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.ForeignKeyConstraint(['user_id'], ['app.user.id'], name=op.f('fk_encounter_streaks_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_encounter_streaks')),
    sa.UniqueConstraint('user_id', name=op.f('uq_encounter_streaks_user_id')),
    schema='devotion',
    comment='Stored longest streak and current-streak write cache (ADR 0012)'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('encounter_streaks', schema='devotion')
    op.drop_index(op.f('ix_encounter_days_user_id'), table_name='encounter_days', schema='devotion')
    op.drop_index(op.f('ix_encounter_days_date'), table_name='encounter_days', schema='devotion')
    op.drop_table('encounter_days', schema='devotion')
    # ### end Alembic commands ###
